name: mlx-plugin
description: This plugin installs MiniLibX Graphics Librabry to create graphical projects.
display-name: mlx-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Project Name
    type: text
    name: project_name
    default: project_name
    global: true

hooks:
  - type: run
    trigger: before-render
    commands:
      - wget https://cdn.intra.42.fr/document/document/14588/minilibx-linux.tgz
      - tar -xvf minilibx-linux.tgz
      - echo "Compiling files..."
      - make -C ./minilibx-linux/
      - echo "Installing lib..."
      - sudo cp ./minilibx-linux/libmlx.a /usr/local/lib/
      - echo "Installing includes..."
      - sudo cp ./minilibx-linux/mlx.h /usr/local/include/
      - echo Done!
  - type: edit
    trigger: after-render
    path: ./Makefile
    changes:
      - insert:
          line: 6
          value: "MLX_FLAGS = -lmlx -lXext -lX11\n\n"
          when:
            not-exists: "MLX_FLAGS= -lmlx -lXext -lX11\n\n"
  - type: edit
    trigger: after-render
    path: ./includes/{{project_name}}.h
    changes:
      - insert:
          line: 3
          value: "# include <mlx.h>\n\n"
          when:
            not-exists: "# include <mlx.h>"
