type: app
description: "The Basics for a C Project: a Folder with the project name,\
 a Makefile to compile the code, a subfolder for src files and include files,\
 and Norminette installed."
# template used to create the project
template: 42-c-projects/42-c-project-template
inputs:
  - label: Install Norminette?
  name: name
  type: text
  items:
        - "Install Norminette"
        - "Skip installation (not necessary)"
  default: "Skip installation (not necessary)"
# list of plugins to be applied after project creation
plugins:
  - plugin: 42-c-projects/mlx-plugin
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
