type: app
description: 42-c-project-template + mlx + libft for graphic projects
# template used to create the project
template: 42-c-projects/42-c-project-template
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: 42-c-projects/mlx-plugin
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
